name: Deploy New Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'IP Address of the Server'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ github.event.inputs.server_ip }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

          script: |
            set -euxo pipefail # Enable detailed debugging

            # Обновить все пакеты и зависимости
            echo "Updating and upgrading packages"
            sudo apt-get update && sudo apt-get upgrade -y || exit 1
            
            # Установка Git если не установлен
            echo "Checking if Git is installed"
            if ! type git >/dev/null 2>&1; then
              echo "Installing Git"
              sudo apt-get install git -y || exit 1
            fi

            # Установка Docker
            echo "Checking if Docker is installed"
            if ! type docker >/dev/null 2>&1; then
              echo "Installing Docker"
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh || exit 1
              sudo usermod -aG docker ${{ secrets.SERVER_USER }} || exit 1
            fi

            # Установка Docker Compose
            echo "Checking if Docker Compose is installed"
            if [ ! -f /usr/local/bin/docker-compose ]; then
              echo "Installing Docker Compose"
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose || exit 1
            fi

            # Проверка и создание Docker сети
            echo "Checking for Docker network"
            if ! docker network ls | grep -q my-network; then
              echo "Creating Docker network"
              docker network create my-network || true
            fi

            # Настройка ключей GitHub
            echo "Setting up GitHub keys"
            if [ ! -f /root/.ssh/id_rsa ]; then
              mkdir -p /root/.ssh
              echo "${{ secrets.DEPLOY_KEY }}" > /root/.ssh/id_rsa
              chmod 600 /root/.ssh/id_rsa || exit 1
              ssh-keyscan github.com >> /root/.ssh/known_hosts || exit 1
              echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
            fi

            # Настройка Git
            echo "Configuring Git"
            git config --global user.name "AbaddonTi" || exit 1
            git config --global user.email "ctekta@gmail.com" || exit 1

            # Клонирование или обновление репозитория
            echo "Cloning or updating repository"
            REPO_PATH="/root/Neural-Nid"
            if [ ! -d "$REPO_PATH" ]; then
              git clone git@github.com:AbaddonTi/Neural-Nid.git $REPO_PATH || exit 1
            else
              cd $REPO_PATH
              git pull || exit 1
            fi

            # Установка SSL сертификата
            echo "Installing SSL certificate"
            if ! [ -f /etc/letsencrypt/live/neuronalnid.com/fullchain.pem ]; then
              sudo apt-get install certbot python3-certbot-nginx -y || exit 1
              sudo certbot --nginx -d neuronalnid.com -d www.neuronalnid.com || exit 1
            fi

            # Обновление конфигурации nginx
            echo "Updating nginx configuration"
            if [ -f /root/Neural-Nid/backup/nginx/default ]; then
              sudo cp /root/Neural-Nid/backup/nginx/default /etc/nginx/sites-available/default || exit 1
              sudo systemctl reload nginx || exit 1
            fi

            echo "Server setup complete successfully"
            exit 0  # Успешное завершение работы скрипта
