name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sparse Checkout
        uses: actions/checkout@v2
        with:
          path: 'Neural-Nid'
          sparse-checkout: 'backend/*'

      - name: Build and Deploy Backend Container
        run: |
          cd Neural-Nid/backend
          docker stop neural-nid-backend || true
          docker rm neural-nid-backend || true
          docker build -t neural-nid-backend .
          docker run -d --restart always --name neural-nid-backend --network=my-network -p 5500:5500 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e STATISTICS_SERVICE_URL=http://statistics-collector:5600/log \
            neural-nid-backend
