name: Deploy Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'statistics/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy to Servers
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVERS_IPS: ${{ secrets.SERVERS_IPS }}
        run: |
          IFS=',' read -ra ADDR <<< "$SERVERS_IPS"
          for IP in "${ADDR[@]}"; do
            (
              echo "Connecting to $IP"
              sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no $SERVER_USER@$IP "
                echo 'Checking for available updates'
                NEED_UPDATE=\$(sudo apt-get upgrade -u -s | grep -P '^\\d+ upgraded' | cut -d ' ' -f 1)
                if [[ \"\$NEED_UPDATE\" != '0' ]]; then
                  echo 'Updating and upgrading packages as updates are available'
                  sudo apt-get update && sudo apt-get upgrade -y
                else
                  echo 'No updates are necessary at the moment'
                fi

                echo 'Checking if Git is installed'
                if ! type git >/dev/null 2>&1; then
                  echo 'Installing Git'
                  sudo apt-get install git -y
                fi
              "
            ) &
          done
          wait
