name: Deploy Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'statistics/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH and Deploy to Servers
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          SERVERS_IPS="${{ secrets.SERVERS_IPS }}"
          IFS=',' read -ra ADDR <<< "$SERVERS_IPS"
          for IP in "${ADDR[@]}"; do
            (
              # Use sshpass to pass the SSH password and execute the script
              OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
              sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no $SERVER_USER@$IP "export OPENAI_API_KEY=$OPENAI_API_KEY && bash -s" < ./CI_CD.sh
            ) &
          done
          wait
          # Display logs
          for IP in "${ADDR[@]}"; do
            echo "Logs for server $IP:"
            cat deploy_log_$IP.txt
          done

